### ISSUE TITLE
FR1. Placing virtual Products in their environment

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#1]
|FR1. Placing virtual Products in their environment|
|---|
|**Goal**: Users will have a rear camera view of placing virtual products into their rooms or real space.
**Stakeholders:** Customers|
| **Description:** When a customer selects a product or store, he/she should be able to virtually display and place the product in their real space using the camera. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 10 |

**Comment by Bryan-Lor** [comment]
Jesse has completed this task, he will create a PR to push to main when he is able
