### ISSUE TITLE
FR16: Load 3D models from database when selected

### ISSUE THREAD

**Issue by Jessku** [WSU-4110/AR-Interior-Design#10]
|FR16: Load 3D models from database when selected|
|---|
|**Goal**: The system will seamlessly load into view a 3D model when prompted.
**Stakeholders:** Customers|
| **Description:** When a customer sees a product they're interested in, they will have the ability to load it into view if the item has a corresponding model within the database. Models should be asynchronously downloaded and imported. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/4/2024
| **Priority:** 1 |

**Comment by roryslange** [comment]
Not completed, time was spent on React Native Unity Integration.
