### ISSUE TITLE
FR9. Filtering products by cost and rating

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#11]
|FR9. Filtering through products when it comes to price range and rating|
|---|
|**Goal**: Filtering through products when it comes to price range, rating.
**Stakeholders:** Customers|
| **Description:** Users should be able to filter through products easily based on price and rating. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 3 |

**Comment by Bryan-Lor** [comment]
Completed by Kasataya in Sprint 3, view [PR 51](https://github.com/WSU-4110/AR-Interior-Design/pull/51)
