### ISSUE TITLE
FR10. Filtering product category by stores

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#12]
|FR10. Filtering product category by stores|
|---|
|**Goal**: User should be able to filter through stores
**Stakeholders:** Customers|
| **Description:** Customers should be able to go through store names and filter them based on the products they offer. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 2 |

**Comment by Bryan-Lor** [comment]
Completed by Kasataya in Sprint 3, view [PR 51](https://github.com/WSU-4110/AR-Interior-Design/pull/51)
