### ISSUE TITLE
FR.11  Filtering product category by brand

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#13]
|FR11. Filtering product category by brand|
|---|
|**Goal**: Products filtered by brand by user.
**Stakeholders:** Customers|
| **Description:** Users have the ability to filter the products based off brand. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 1 |

**Comment by Bryan-Lor** [comment]
Completed by Kasataya in Sprint 3, view [PR 51](https://github.com/WSU-4110/AR-Interior-Design/pull/51)
