### ISSUE TITLE
FR12. Create an Account

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#16]
|FR12. Users could create an account|
|---|
|**Goal**: Users will have the option to select a button that lets them create an account incase they do not have one.
**Stakeholders:** Customers|
| **Description:** Incase the user does not have a registered account he will be able to navigate to a screeen that allows him to. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 6 |

**Comment by Bryan-Lor** [comment]
Picked up alongside user log in/out 2/8/2024

- [x] Created sign up page which can be switched into from login, also has option to go back
- [x] Users can create account with email
- [ ] Users can create account with GitHub

**Comment by Bryan-Lor** [comment]
GitHub account creation can be backlogged as it will require more effort to complete. For now, the core login/signout implementation is live and pushed to main. [Here is the link to the PR.](https://github.com/WSU-4110/AR-Interior-Design/pull/33)
