### ISSUE TITLE
FR.13 Favorite products

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#18]
|FR.13 Favorite products|
|---|
|**Goal**: Users will have the ability to favorite and save products.
**Stakeholders:** Customers|
| **Description:** Customers can keep track of saved products. This can then later be viewed easily. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 5 |

**Comment by Bryan-Lor** [comment]
Pulled into Sprint2 and completed in [PR 48](https://github.com/WSU-4110/AR-Interior-Design/pull/48)
