### ISSUE TITLE
FR14. Customer Ratings

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#19]
|FR14. Customer Ratings|
|---|
|**Goal**: Customers can leave 5-star ratings on products.
**Stakeholders:** Customers|
| **Description:** You should be able to rate products and get a final product score on a 5-star scale. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 3 |

**Comment by roryslange** [comment]
Backlogged, focused on more important functionality of the project.
