### ISSUE TITLE
FR2. Virtual Product navigation

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#2]
|FR2. Customers navigating through products|
|---|
|**Goal**: Once a customer selects the desired store and the product, similar products should be accessible simply through the application as well. 
**Stakeholders:** Customers|
| **Description:** Incase the customer wants to check out similar products in the store he should be able to easily switch through these products while he has his camera open. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 4 |

**Comment by roryslange** [comment]
Not completed, required unity integration.
