### ISSUE TITLE
FR15. Customer Review

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#20]
|FR15. Customer Review|
|---|
|**Goal**: Customers can leave a review on the product. 
**Stakeholders:** Customers|
| **Description:** Users should be able to leave a review/comment after purchasing the product.|
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:**02/04/2024
| **Priority:** 1 |

**Comment by roryslange** [comment]
Backlogged, focused on more important requirements.
