### ISSUE TITLE
FR16. Product Rotation Controls

### ISSUE THREAD

**Issue by Bryan-Lor** [WSU-4110/AR-Interior-Design#21]
|FR16. Product Rotation Controls|
|---|
|**Goal**: Users can freely rotate the product within AR view.
**Stakeholders:** Customers|
| **Description:** Users should be able to easily control the rotation of a product when viewing in AR. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 7 |

**Comment by roryslange** [comment]
completed by Jessee throughout project.
