### ISSUE TITLE
NR5: Security

### ISSUE THREAD

**Issue by Bryan-Lor** [WSU-4110/AR-Interior-Design#22]
|NR5: Security|
|---|
|**Goal**: Backend should be properly secured and restricted.
**Stakeholders:** All|
| **Description:** Only specified users should have access to backend and API calls. Best practices should also be followed to keep the information secure. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 10 |

**Comment by roryslange** [comment]
maintained throughout project.
