### ISSUE TITLE
FR17. Product Color Variation

### ISSUE THREAD

**Issue by Bryan-Lor** [WSU-4110/AR-Interior-Design#23]
|FR17. Product Color Variation|
|---|
|**Goal**: Users can swap to different variations of the product within AR view.
**Stakeholders:** Customers|
| **Description:** Users should be able to easily swap the color/variation of a product when viewing in AR. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 5|

**Comment by Jessku** [comment]
Decided to push back to sprint 3 because it's a "want," instead of a "need."

**Comment by roryslange** [comment]
Backlogged, focused on other more important requirements instead
