### ISSUE TITLE
FR19: Dark mode support

### ISSUE THREAD

**Issue by roryslange** [WSU-4110/AR-Interior-Design#29]
### Goal

Change styles to adapt to dark mode

### Description

Currently when the app is run in dark mode the contrast of some of the windows is too high. Styles of the react app should be changed to smoothly transition to dark mode. 

### Stakeholders

All

### Date

2/15/2024

### Version

1.0

### Origin

Discovered when styling cards for the catalog view.

### Priority of the proposed feature

Should have

**Comment by Bryan-Lor** [comment]
Resolved early in Sprint 1, can mark as closed
