### ISSUE TITLE
FR.3 Customer Log In/Out

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#3]
|FR.3 Customer Log In/Out|
|---|
|**Goal**: Customers should be able to log in and log out of the application.
**Stakeholders:** Customers|
| **Description:** Customers will have the ability to create and log in or out of the application for privacy reasons. |
| **Origin:** Based on the initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 10 |

**Comment by Bryan-Lor** [comment]
Picked up issue alongside setting up backend 2/8/2024

- [x] Set up authentication
- [x] Set up front-end login page
- [x] Updated routers to first direct to login 
- [x] Users can log in/out

**Comment by Bryan-Lor** [comment]
Changes have been pushed to main. [Here is the PR](https://github.com/WSU-4110/AR-Interior-Design/pull/33)
