### ISSUE TITLE
FR.20 Item Details Page

### ISSUE THREAD

**Issue by Bryan-Lor** [WSU-4110/AR-Interior-Design#31]
|FR18. Database Stores User Info|
|---|
|**Goal**: Display details of selected product
**Stakeholders:** Customers|
| **Description:**When user clicks on an item in the Items Catalog page, they will be routed to the Items Details Page. We need to create a dynamic page that will load the name, cost, and price of the item selected. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/22/2024
| **Priority:** 5|

**Comment by Bryan-Lor** [comment]
Mohommad has completed the task and pulled into main [here](https://github.com/WSU-4110/AR-Interior-Design/pull/35)

**Comment by roryslange** [comment]
item details page now uses data from backend that is passed in index.tsx
