### ISSUE TITLE
FR4. Virtual product data base

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#4]
|FR4. Virtual product data base
|---|
|**Goal**: Set up database
**Stakeholders:** Customers|
| **Description:** We will be using Firebase to store 3D models and transition them into our application. This will help ensure a seamless transition when it comes to importing 3D models inside the application. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 10 |

**Comment by Bryan-Lor** [comment]
Picked up issue and began Firebase setup 2/6/2024
- [x] Create Firebase backend - [2/6/2024]
- [x] Add firebase js sdk into ReactNative application - [2/8/2024]
- [x] Set up .env and API keys - [2/8/2024]
- [x] Confirm that we can communicate to Firebase

**Comment by Bryan-Lor** [comment]
Firebase connection has been established with our application. Changes have been pushed to main. [Here is the PR](https://github.com/WSU-4110/AR-Interior-Design/pull/33)
