### ISSUE TITLE
FR5. Transition between the item catalogs and AR view

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#5]
|FR5. Transition between the item catalogs and AR view|
|---|
|**Goal**: Customers should be able to transition smoothly from the AR camera view back into the catalog view.
**Stakeholders:** Customers|
| **Description:** Once a customer is done using the AR camera mode he/she can easily go back to the store catalog they are currently in. |
| **Origin:** Based on initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 5 |

**Comment by roryslange** [comment]
Not completed, Unity was not able to be integrated.
