### ISSUE TITLE
FR7. Camera Device access

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#7]
|FR7. Camera Device access|
|---|
|**Goal**: The application can access the device's camera.
**Stakeholders:** Customers|
| **Description:** Application should be able to access the user's device camera when in need of testing out a product. |
| **Origin:** Based on the initial project specification document, team
members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 10 |

**Comment by Bryan-Lor** [comment]
Team has decided this is no longer needed since Unity automatically retrieves access to Camera device.
