### ISSUE TITLE
FR8. Redirect to the main page after login.

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#9]
|FR8. Redirect to the main page after login.|
|---|
|**Goal**: Once the user has logged into his account he should be directed to the main page in the application
**Stakeholders:** Customers|
| **Description:** When a customer logs into the application the first thing he should be seeing is the list of stores within the database. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 7 |

**Comment by Bryan-Lor** [comment]
Completed this while working on login and setup pages. [You can view the PR here](https://github.com/WSU-4110/AR-Interior-Design/pull/33)
